// src/adapters/react-native/components/Guards/AuthGuard.tsx
// src/adapters/react-native/components/Guards/AuthGuard.tsx
import React from 'react';
import { View, ActivityIndicator, StyleSheet } from 'react-native';
import { useAuth } from '../../hooks/useAuth';
import type { ViewStyle } from 'react-native';

interface AuthGuardProps {
  children: React.ReactNode;
  fallback?: React.ComponentType;
  onUnauthenticated?: () => void;
  loading?: React.ComponentType;
  style?: ViewStyle;
  loadingStyle?: ViewStyle;
}

export function AuthGuard({
  children,
  fallback: FallbackComponent,
  onUnauthenticated,
  loading: LoadingComponent,
  style,
  loadingStyle,
}: AuthGuardProps) {
  const { session, loading } = useAuth();

  React.useEffect(() => {
    if (!loading && !session && onUnauthenticated) {
      onUnauthenticated();
    }
  }, [loading, session, onUnauthenticated]);

  if (loading) {
    return LoadingComponent ? (
      <LoadingComponent />
    ) : (
      <View style={[styles.container, loadingStyle]}>
        <ActivityIndicator size="large" />
      </View>
    );
  }

  if (!session) {
    return FallbackComponent ? <FallbackComponent /> : null;
  }

  return <View style={style}>{children}</View>;
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
});

// src/adapters/svelte/components/Guards/AuthGuard.svelte
<!-- src/adapters/svelte/components/Guards/AuthGuard.svelte -->
<script lang="ts">
    import { auth } from '../../stores/auth';
  
    export let fallback: any = undefined;
    export let onUnauthenticated: () => void = undefined;
  
    $: if (!$auth.loading && !$auth.session && onUnauthenticated) {
      onUnauthenticated();
    }
  </script>
  
  {#if $auth.loading}
    <div>Loading...</div>
  {:else if !$auth.session}
    {#if fallback}
      <svelte:component this={fallback} />
    {/if}
  {:else}
    <slot />
  {/if}
