// src/adapters/react/components/Guards/AuthGuard.tsx
// src/adapters/react/components/Guards/AuthGuard.tsx
import { useEffect } from 'react';
import React from 'react';
import { useAuth } from '../../hooks/useAuth';

interface AuthGuardProps {
  children: React.ReactNode;
  fallback?: React.ReactNode;
  onUnauthenticated?: () => void;
}

export function AuthGuard({ children, fallback, onUnauthenticated }: AuthGuardProps) {
  const { session, loading } = useAuth();

  useEffect(() => {
    if (!loading && !session && onUnauthenticated) {
      onUnauthenticated();
    }
  }, [loading, session, onUnauthenticated]);

  if (loading) {
    return fallback || null;
  }

  if (!session) {
    return null;
  }

  return <>{children}</>;
}

// src/adapters/svelte/components/Guards/AuthGuard.svelte
<!-- src/adapters/svelte/components/Guards/AuthGuard.svelte -->
<script lang="ts">
    import { auth } from '../../stores/auth';
  
    export let fallback: any = undefined;
    export let onUnauthenticated: () => void = undefined;
  
    $: if (!$auth.loading && !$auth.session && onUnauthenticated) {
      onUnauthenticated();
    }
  </script>
  
  {#if $auth.loading}
    <div>Loading...</div>
  {:else if !$auth.session}
    {#if fallback}
      <svelte:component this={fallback} />
    {/if}
  {:else}
    <slot />
  {/if}
