// src/adapters/svelte/components/Guards/RoleGuard.svelte
<!-- src/adapters/svelte/components/Guards/RoleGuard.svelte -->
<script lang="ts">
    import { auth } from '../../stores/auth';
  
    export let roles: string | string[];
    export let fallback: any = undefined;
    export let onUnauthorized: () => void = undefined;
  
    $: isAuthorized = $auth.isAuthorized(roles);
    $: if (!isAuthorized && onUnauthorized) {
      onUnauthorized();
    }
  </script>
  
  {#if !isAuthorized}
    {#if fallback}
      <svelte:component this={fallback} />
    {:else}
      <div>No tiene permisos suficientes</div>
    {/if}
  {:else}
    <slot />
  {/if}

// src/adapters/react/components/Guards/RoleGuard.tsx
// src/adapters/react/components/Guards/RoleGuard.tsx
import React from 'react';
import { useEffect } from 'react';
import { useAuth } from '../../hooks/useAuth';

interface RoleGuardProps {
  children: React.ReactNode;
  roles: string | string[];
  fallback?: React.ReactNode;
  onUnauthorized?: () => void;
}

export function RoleGuard({ children, roles, fallback, onUnauthorized }: RoleGuardProps) {
  const { session, isAuthorized } = useAuth();
  const hasAccess = isAuthorized(roles);

  useEffect(() => {
    if (!hasAccess && onUnauthorized) {
      onUnauthorized();
    }
  }, [hasAccess, onUnauthorized]);

  if (!session || !hasAccess) {
    return fallback || null;
  }

  return <>{children}</>;
}
