// src/adapters/svelte/components/BridgeView.svelte
<!-- src/adapters/svelte/components/BridgeView.svelte -->
<script lang="ts">
    import { getContext } from 'svelte';
    import { auth } from '../stores/auth';
  
    export let userTypes: string | string[] = undefined;
    export let requireAuth = true;
    export let unauthorized: any = undefined;
    export let loading: any = undefined;
  
    $: isAuthorized = !userTypes || $auth.isAuthorized(userTypes);
    $: showContent = (!requireAuth || $auth.session) && isAuthorized;
  </script>
  
  {#if $auth.loading}
    {#if loading}
      <svelte:component this={loading} />
    {:else}
      <div>Loading...</div>
    {/if}
  {:else if !showContent}
    {#if unauthorized}
      <svelte:component this={unauthorized} />
    {:else}
      <div>No tiene acceso a este recurso</div>
    {/if}
  {:else}
    <slot />
  {/if}

// src/adapters/react-native/components/BridgeView.tsx
// src/adapters/react-native/components/BridgeView.tsx
import React from 'react';
import { View, ActivityIndicator, Text, StyleSheet, ViewStyle } from 'react-native';
import { useAuth } from '../hooks/useAuth';

interface BridgeViewProps {
  children: React.ReactNode;
  userTypes?: string | string[];
  requireAuth?: boolean;
  onUnauthorized?: () => void;
  loading?: React.ComponentType;
  unauthorized?: React.ComponentType;
  style?: ViewStyle;
  loadingStyle?: ViewStyle;
  unauthorizedStyle?: ViewStyle;
}

export function BridgeView({
  children,
  userTypes,
  requireAuth = true,
  onUnauthorized,
  loading: LoadingComponent,
  unauthorized: UnauthorizedComponent,
  style,
  loadingStyle,
  unauthorizedStyle
}: BridgeViewProps) {
  const { session, loading, isAuthorized } = useAuth();

  React.useEffect(() => {
    if (!loading && requireAuth && !session) {
      onUnauthorized?.();
    }
  }, [loading, session, requireAuth]);

  if (loading) {
    return LoadingComponent ? (
      <LoadingComponent />
    ) : (
      <View style={[styles.container, loadingStyle]}>
        <ActivityIndicator size="large" />
      </View>
    );
  }

  if (requireAuth && !session) {
    return null;
  }

  if (userTypes && !isAuthorized(userTypes)) {
    return UnauthorizedComponent ? (
      <UnauthorizedComponent />
    ) : (
      <View style={[styles.container, unauthorizedStyle]}>
        <Text style={styles.unauthorizedText}>
          No tiene acceso a este recurso
        </Text>
      </View>
    );
  }

  return <View style={style}>{children}</View>;
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  unauthorizedText: {
    fontSize: 16,
    textAlign: 'center',
    color: '#666',
  },
});
